Ipfs Pinata Tests
ecadlabs/taqueria pull request #1144
Opened 2022-08-18 04:32 UTC by ricklove

- tests for ipfs-pinata plugin

### NOTE: These tests require an .env variable to be provided with a pinata api keys.

- For CICD tests, these ENV VARS should be added to secrets:

```
pinataApiKey=b547...
pinataApiSecret=42b...
pinataJwtToken=eyJ...
```

2022-08-19 17:14 UTC, sinapsist approved these changes
LGTM

2022-08-19 17:14 UTC, jchenche approved these changes

2022-08-23 17:27 UTC, GImbrailo commented
@hu3man @alexzbusko here is the PR I was talking about earlier.

2022-08-23 17:43 UTC, hu3man commented
Oops looks like I did delete the branch by accident 🤦‍♂️

Opening back up and assigning to @alexzbusko to drive

2022-08-30 17:06 UTC, GImbrailo requested changes

2022-08-30 17:06 UTC, GImbrailo commented on .github/workflows/main.yml
> +      - 893-ipfs-pinata-pin-task
Should this line be removed before merging into `main`?

2022-09-01 17:14 UTC, merged