🏗️  ➾Re-enable Contract Types Plugin Publishing
ecadlabs/taqueria pull request #1184
Opened 2022-08-24 17:46 UTC by hu3man

## 🪂 Pre-Merge Checklist

N/A

----------------------------------------------------------------------------------------------------------------------------

## 🪁 Description

The publish step for the Contract Types plugin has been disabled since the 0.10.0 release of Taqueria. As such, the plugin is now 2 versions behind the rest of Taqueria and has caused a user-reported bug. This PR re-enables the skipped steps in `main.yml` 

> Note: I have manually published v0.12.0 of the plugin  

## 🎢 Test Plan

N/A

----------------------------------------------------------------------------------------------------------------------------

### 🛸 Type of Change

- [x] 🐟 Minor change (non-breaking change of very limited scope)
- [ ] 🦑 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🌊 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🐳 Major refactor (breaking changes and significant impact to the codebase)

----------------------------------------------------------------------------------------------------------------------------

2022-08-24 18:16 UTC, alexzbusko approved these changes

2022-08-29 23:53 UTC, GImbrailo requested changes

2022-08-29 23:53 UTC, GImbrailo commented on .github/workflows/main.yml
> +    # needs: publish-sdk-to-npm
This comment needs to be removed as `contract-types` depends on `taqueria-sdk`

2022-08-30 19:35 UTC, GImbrailo approved these changes
LGTM

2022-08-30 19:38 UTC, merged