1042 invalid configuration message
ecadlabs/taqueria pull request #1262
Opened 2022-09-22 16:57 UTC by mweichert

# 🏗️ PR ➾ 1042

Fixes #1042 

## 🪂 Pre-Merge Checklist

- [x] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🏄‍♂️ Myself and others have built this branch and done manual testing on the change
- [ ] ⛵ A summary describing the change has been written for release notes

----------------------------------------------------------------------------------------------------------------------------

## 🪁 Description

### Add error hinting:

Any configuration error in .taq/config.json would result in the following unhelpful message:
```
[object Object] is not a configuration
```

This PR adds much more error hinting:
```
Your .taq/config.json file is invalid:
  network → ghostnet → faucet → email: Invalid
```

### Relax faucet validation constraints

Now that teztnets.xyz doesn't provide faucet files, we need to adjust and relax the validation routines around faucet configurations so that email, password, and activation_code are optional.

## 🎢 Test Plan

I'm developing E2E tests that assure:
- Error hints are displayed properly
- Faucets can be entered without email, password, or activation_code fields.

----------------------------------------------------------------------------------------------------------------------------

### 🛸 Type of Change

- [ ] 🐟 Minor change (non-breaking change of very limited scope)
- [x] 🦑 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🌊 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🐳 Major refactor (breaking changes and significant impact to the codebase)

----------------------------------------------------------------------------------------------------------------------------

2022-09-23 14:15 UTC, AlirezaHaghshenas approved these changes

2022-09-23 16:50 UTC, hu3man approved these changes

2022-09-26 15:49 UTC, hu3man requested changes
The code looks good, needs documentation or comms strategy to meet defOfDone

2022-09-27 16:10 UTC, jchenche approved these changes

2022-09-27 19:04 UTC, AlirezaHaghshenas approved these changes

2022-09-27 20:07 UTC, hu3man approved these changes

2022-09-28 21:49 UTC, merged