Update mechanism for funding accounts
ecadlabs/taqueria pull request #1295
Opened 2022-09-29 19:08 UTC by jchenche

# 🏗️ PR ➾

Fixes # (issue)

## 🪂 Pre-Merge Checklist

- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🏄‍♂️ Myself and others have built this branch and done manual testing on the change
- [ ] ⛵ A summary describing the change has been written for release notes

----------------------------------------------------------------------------------------------------------------------------

## 🪁 Description

Please include a summary of the change and add the issue number this is related to above. Please also include relevant motivation and context for the change
(e.g. what was the existing behavior, why did it break, etc.)

## 🎢 Test Plan

Please describe the testing strategy for this change

----------------------------------------------------------------------------------------------------------------------------

### 🛸 Type of Change

- [ ] 🐟 Minor change (non-breaking change of very limited scope)
- [ ] 🦑 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🌊 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🐳 Major refactor (breaking changes and significant impact to the codebase)

----------------------------------------------------------------------------------------------------------------------------

2022-09-29 23:09 UTC, hu3man approved these changes
Excellent work! The UX is great for an MVP and it dramatically improves on the faucet file flow

Tests are still failing it looks like but the code and CLI output both look good to me 👍

I do want to have the teztnets link clickable, but that can come in a later iteration

2022-10-03 18:13 UTC, AlirezaHaghshenas approved these changes

2022-10-05 19:19 UTC, hu3man requested changes

2022-10-05 19:19 UTC, hu3man commented on taqueria-plugin-taquito/transfer.ts
> +							`${publicKeyHash} possibly has no funds. Go to https://teztnets.xyz and click "Faucet" of the desired protocol to fund it. Note that you might need to wait for a few seconds for the network to
The root account {publicKeyHask} for the target environment may not be funded \n
To fund this account:
1. Go to https://teztnets.xyz and click "Faucet" of the target testnet
2. Copy and paste {publicKeyHash} into the 'wallet address field
3. Request some Tez
(Note that you might need to wait for a few seconds for the network to register the funds)

2022-10-05 19:19 UTC, hu3man commented on taqueria-sdk/index.ts
> +			} was generated for you. Go to https://teztnets.xyz and click "Faucet" of the desired protocol to fund it.`,
Same instructions as above

2022-10-05 21:03 UTC, hu3man approved these changes

2022-10-05 21:03 UTC, hu3man commented
Still need doc updates right?

2022-10-05 21:36 UTC, jchenche commented
> Still need doc updates right?

@hu3man I made the updates as part of the ghostnet addition.

2022-10-05 23:22 UTC, hu3man approved these changes

2022-10-06 01:44 UTC, merged