implement lambda typescript generation
ecadlabs/taqueria pull request #1433
Opened 2022-10-31 23:33 UTC by AlirezaHaghshenas

# 🌮 Taqueria PR

## 🪁 Description

_Explain it to me like I'm 5! Keep this short and descriptive_

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

_Please include a summary of the changes to the codebase._ _Please also include relevant motivation and context for the change_
_(e.g. what was the existing behaviour, why did it break, etc.)_

## 🎢 Test Plan

_Please describe the testing strategy and plan for this PR. Keep this lightweight and anticipate any testing challenges_

## 🛸 Type of Change

- [ ] 🧽 Chore ➾
- [ ] 🛠️ Fix ➾
- [ ] ✨ Feature ➾
- [ ] 👷 Refactor ➾
- [ ] 🧪 Pre-Release ➾
- [ ] 🚀 Release ➾

2022-11-01 16:17 UTC, ricklove reviewed
Looks right, just need to add e2e tests and add some contracts and expected output:

https://github.com/ecadlabs/taqueria/blob/1e667b348309fa1b656a66f4dc94a91376384fee/tests/e2e/taqueria-plugin-contract-types.spec.ts#L235

2022-11-01 22:13 UTC, jchenche commented
Don't we need to define `lambda` in `taqueria-plugin-contract-types/src/type-aliases.ts`?

2022-11-02 16:54 UTC, AlirezaHaghshenas commented
> Don't we need to define `lambda` in `taqueria-plugin-contract-types/src/type-aliases.ts` to be exported?

No, we don't use lambda directly in ts. We use arrow signature: `(args: argType) => retType` which does not need any type alias.

Unless I'm not aware of something

2022-11-02 16:56 UTC, ricklove commented
> Don't we need to define `lambda` in `taqueria-plugin-contract-types/src/type-aliases.ts` to be exported?

Ah right: this will probably need additional generics added to Taquito, but we will need something here:

type contractTypes = { methods: Methods, methodsObject: MethodsObject, storage: Storage, code: { __type: 'ExampleLambdaCode', protocol: string, code: object[] } };

2022-11-02 17:01 UTC, ricklove commented
Hmm, actually the taquito generics might work, we might just need to modify this file to put the lambda type in the correct place (views?)

2022-11-02 17:03 UTC, ricklove commented
We also need to add a usage example here which will help verify if it is working right:

https://github.com/ecadlabs/taqueria/blob/refactor-protocal/taqueria-plugin-contract-types/example/example-usage.ts#L6

2022-11-02 21:16 UTC, hu3man commented
Please update the title of this PR with the icon and proper capitalization when you have time @AlirezaHaghshenas

2022-11-02 22:11 UTC, AlirezaHaghshenas commented
@ricklove 

> Hmm, actually the taquito generics might work, we might just need to modify this file to put the lambda type in the correct place (views?)

I actually don't know what you're talking about. I might need more context

2022-11-08 19:25 UTC, hu3man approved these changes
Great work @AlirezaHaghshenas!

2022-11-09 21:12 UTC, ricklove requested changes
Need to add a helper to create a lambda

2022-11-09 21:12 UTC, ricklove commented on taqueria-plugin-contract-types/src/generator/typescript-output.ts
> +			throw new GenerateApiError(`Don't know how to generate default value for lambda`, { t });
Hmm, this warrants a new helper in the tas utils, so this should be something like this:

```
return `tas.intruction('')`
```

Also, this needs to be added to the tas code to convert a string to a MichelsonInstruction

2022-11-10 23:40 UTC, ricklove approved these changes
Nice!

2022-11-11 01:07 UTC, merged