Check for deno version
ecadlabs/taqueria pull request #1589
Opened 2022-12-07 20:14 UTC by mweichert

# 🌮 Taqueria PR

## 🪁 Description

Taqueria requires Deno v1.23.X to build. This branch adjusts the build.sh and build-all.sh scripts to ensure that Deno is installed and set to the correct version.

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🔱 The test plan has been implemented and verified by an SDET
- [ ] 🦀 Automated tests have been written and added to this PR
- [ ] 🐬 I have commented my code, particularly in hard-to-understand areas
- [ ] 🤿 Corresponding changes have been made to all documentation
- [ ] 🐚 Required changes to the VScE have been made
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

Modified build.sh and build-all.sh scripts. 

## 🎢 Test Plan

I've tested that if I have Deno v1.24 installed I'll get an error when running `npm run build-all`. I've also verified that the error goes away when I have v1.23 installed.

## 🛸 Type of Change

- [ ] 🧽 Chore ➾

2022-12-07 20:20 UTC, danielelisi approved these changes

2022-12-07 20:23 UTC, AlirezaHaghshenas approved these changes

2022-12-07 20:27 UTC, jchenche requested changes

2022-12-07 21:47 UTC, jchenche approved these changes

2022-12-12 11:48 UTC, mweichert commented on bin/build-all.sh
> +            echo "❌ Deno is installed, but not using v1.23.x. Please use Deno v1.23.x."
I have, yes.

2022-12-12 15:24 UTC, mweichert commented on bin/build-all.sh
> +        echo -2
It's an exit code., but `echo` is a typo - it should have been `exit`.

2022-12-12 22:44 UTC, merged