🛠️ Fix ➾ Remove parcel and lmdb (and indirectly clang) as dev dependencies
ecadlabs/taqueria pull request #1640
Opened 2022-12-15 20:27 UTC by mweichert

# 🌮 Taqueria PR

## 🪁 Description

In the release-v0.26.0 branch, the package-lock.json includes reference to a version of parcel which had a dependency on a version lmdb that required the end-developer to have `clang` installed.

## 🪂 Pre-Merge Checklist (Definition of Done)

🚦 Required to merge:

- [ ] ⛱️ I have completed this PR template in full and updated the title appropriately
- [ ] ⛵ My code builds cleanly, and I have manually tested the changes
- [ ] 🏄‍♂️ Another team member has built this branch and done manual testing on the change
- [ ] 🏖️ New and existing unit tests pass locally and in CI
- [ ] 🪸 Required updates to scaffolds have been made
- [ ] 🚢 The release checklist has been completed

## 🛩️ Summary of Changes

As parcel and lmdb have been problematic in the past (lmdb is the culrprit for why native Windows builds don't work), I've replaced parcel with tsup, which is what we've been using for our latest plugins. This removes two fairly heavy and problematic node packages.

## 🎢 Test Plan

I've manually verified that each package can build correctly, and relying on existing E2E tests to assure that packages continue to work as they did before.

2022-12-15 20:43 UTC, hu3man approved these changes

2022-12-19 18:15 UTC, jchenche approved these changes

2022-12-19 18:19 UTC, jchenche requested changes

2022-12-19 18:19 UTC, jchenche commented on taqueria-plugin-jest/package.json
>  		"@taquito/signer": "^13.0.1",
Some are still 13.0.1

E.g. here and in other areas

2022-12-20 18:54 UTC, jchenche approved these changes

2022-12-20 21:14 UTC, merged